service: life-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

functions:
  getSets:
    handler: src/dataGrabbers/sets.handler
    events:
      - schedule:
          rate: rate(1 day)
          enabled: false
  api:
    handler: src/monzo/auth/callback/index.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-esbuild
  - serverless-offline
